version: '3'
services:
  app:
    build: ./php_apache
    container_name: app
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - mongodb
      - redis
    environment:
      TZ: 'Asia/Tokyo'

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/x86_64
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d  #初期処理のフォルダ
#      - ./mysql/conf.d:/etc/mysql/conf.d  #confファイル  see: https://hub.docker.com/_/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_volume:/data/db
      - ./mongodb/initdb.d:/docker-entrypoint-initdb.d  #初期処理のフォルダ
#      - ./mongod.conf:/etc/mongod.conf  #confファイル  see: https://hub.docker.com/_/mongo
#    command: --config /etc/mongod.conf  #confファイルの読み込み
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    volumes:
      - redis_volume:/data
#      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  #confファイル  see: https://hub.docker.com/_/redis
#    command: redis-server /usr/local/etc/redis/redis.conf  #confファイルの読み込み
    environment:
      TZ: 'Asia/Tokyo'

volumes:
  mysql_volume:
  mongo_volume:
  redis_volume:
