version: '3'
services:
  app:
    build: ./php_apache
    container_name: app
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - mongodb
      - redis
    environment:
      TZ: 'Asia/Tokyo'

  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/x86_64
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
      - "./mysql/initdb.d:/docker-entrypoint-initdb.d"  #初期処理のフォルダ
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_volume:/data/db
      - "./mongodb/initdb.d:/docker-entrypoint-initdb.d"  #初期処理のフォルダ
    environment:
      # 接続情報
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    volumes:
      - redis_volume:/data
    environment:
      TZ: 'Asia/Tokyo'

volumes:
  mysql_volume:
  mongo_volume:
  redis_volume:
