FROM php:8.1-apache

## apt
RUN apt-get update \
    && apt-get install -y libzip-dev zlib1g-dev libbz2-dev libyaml-dev \
    ## ssl enable (mongodb接続時のエラー対策)
    libcurl4-openssl-dev pkg-config libssl-dev

## pecl yaml,redis,mongodb
RUN pecl install yaml-2.2.2 && docker-php-ext-enable yaml
RUN pecl install redis && docker-php-ext-enable redis
RUN pecl install mongodb && docker-php-ext-enable mongodb

## ext zip, bz2, mysql
RUN docker-php-ext-install zip bz2
RUN docker-php-ext-install pdo_mysql

# 高速化セット opcache apcu xdebug
RUN docker-php-ext-install opcache && docker-php-ext-enable opcache

# Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# finally php.ini composer.phar
COPY php.ini /usr/local/etc/php/
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Apache
RUN cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load
